--------------------------------------------------------
--  File created - Pazar-Aðustos-15-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Type USER_TABLE_TYPE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "LOCALHOST"."USER_TABLE_TYPE" 
AS TABLE OF USER_TYPE;

/
--------------------------------------------------------
--  DDL for Type USER_TYPE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "LOCALHOST"."USER_TYPE" AS OBJECT 
( USER_ID NUMBER,
USER_NAME VARCHAR2(500),
USER_SURNAME VARCHAR2(500),
USER_TITLE VARCHAR2(500),
WORK_CITY VARCHAR2(500),
USER_SALARY NUMBER,
USER_MANAGER VARCHAR2(500)
)

/
--------------------------------------------------------
--  DDL for Sequence LOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LOCALHOST"."LOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence USER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LOCALHOST"."USER_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table USER_LOG
--------------------------------------------------------

  CREATE TABLE "LOCALHOST"."USER_LOG" 
   (	"LOG_ID" NUMBER(20,0) DEFAULT "LOCALHOST"."LOG_SEQ"."NEXTVAL", 
	"USER_ID" NUMBER(20,0), 
	"FIELD_NAME" VARCHAR2(500 BYTE), 
	"OLD_VALUE" VARCHAR2(500 BYTE), 
	"NEW_VALUE" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_RECORDS
--------------------------------------------------------

  CREATE TABLE "LOCALHOST"."USER_RECORDS" 
   (	"USER_ID" NUMBER DEFAULT "LOCALHOST"."USER_SEQ"."NEXTVAL", 
	"USER_NAME" VARCHAR2(500 BYTE), 
	"USER_SURNAME" VARCHAR2(500 BYTE), 
	"USER_TITLE" VARCHAR2(500 BYTE), 
	"WORK_CITY" VARCHAR2(500 BYTE), 
	"USER_SALARY" NUMBER, 
	"USER_MANAGER" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger USER_LOG_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "LOCALHOST"."USER_LOG_TRIGGER" 
BEFORE UPDATE ON USER_RECORDS
FOR EACH ROW
BEGIN
 
    IF :OLD.USER_NAME != :NEW.USER_NAME and :NEW.USER_NAME is not null then
    insert into user_log (USER_ID,FIELD_NAME,OLD_VALUE,NEW_VALUE) VALUES (:new.USER_ID,'USER_NAME',:old.USER_NAME,:new.USER_NAME);
    END IF;
    IF :OLD.USER_SURNAME != :NEW.USER_SURNAME and :NEW.USER_SURNAME is not null then
    insert into user_log (USER_ID,FIELD_NAME,OLD_VALUE,NEW_VALUE) VALUES (:new.USER_ID,'USER_SURNAME',:old.USER_SURNAME,:new.USER_SURNAME);
    END IF;
    IF :OLD.USER_TITLE != :NEW.USER_TITLE and :NEW.USER_TITLE is not null then
    insert into user_log (USER_ID,FIELD_NAME,OLD_VALUE,NEW_VALUE) VALUES (:new.USER_ID,'USER_TITLE',:old.USER_TITLE,:new.USER_TITLE);
    END IF;
    IF :OLD.WORK_CITY != :NEW.WORK_CITY and :NEW.WORK_CITY is not null then
    insert into user_log (USER_ID,FIELD_NAME,OLD_VALUE,NEW_VALUE) VALUES (:new.USER_ID,'WORK_CITY',:old.WORK_CITY,:new.WORK_CITY);
    END IF;
    IF :OLD.USER_MANAGER != :NEW.USER_MANAGER and :NEW.USER_MANAGER is not null then
    insert into user_log (USER_ID,FIELD_NAME,OLD_VALUE,NEW_VALUE) VALUES (:new.USER_ID,'USER_MANAGER',:old.USER_MANAGER,:new.USER_MANAGER);
    END IF;
    IF :OLD.USER_SALARY != :NEW.USER_SALARY and :NEW.USER_SALARY is not null then
    insert into user_log (USER_ID,FIELD_NAME,OLD_VALUE,NEW_VALUE) VALUES (:new.USER_ID,'USER_SALARY',:old.USER_SALARY,:new.USER_SALARY);
    END IF;
 
 
END;
/
ALTER TRIGGER "LOCALHOST"."USER_LOG_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Function GET_USER_FUNC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "LOCALHOST"."GET_USER_FUNC" RETURN USER_TABLE_TYPE PIPELINED AS
BEGIN

 FOR ELEM IN  (SELECT USER_ID,USER_NAME,USER_SURNAME,USER_TITLE, WORK_CITY, USER_SALARY, USER_MANAGER FROM USER_RECORDS where user_salary>4200 order by USER_NAME asc)
 LOOP
    PIPE ROW(USER_TYPE(ELEM.USER_ID,ELEM.USER_NAME,ELEM.USER_SURNAME,ELEM.USER_TITLE,ELEM.WORK_CITY,ELEM.USER_SALARY,ELEM.USER_MANAGER));
    END LOOP;
END GET_USER_FUNC;

/
--------------------------------------------------------
--  Constraints for Table USER_RECORDS
--------------------------------------------------------

  ALTER TABLE "LOCALHOST"."USER_RECORDS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "LOCALHOST"."USER_RECORDS" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "LOCALHOST"."USER_RECORDS" MODIFY ("USER_SURNAME" NOT NULL ENABLE);
  ALTER TABLE "LOCALHOST"."USER_RECORDS" MODIFY ("USER_TITLE" NOT NULL ENABLE);
  ALTER TABLE "LOCALHOST"."USER_RECORDS" MODIFY ("WORK_CITY" NOT NULL ENABLE);
  ALTER TABLE "LOCALHOST"."USER_RECORDS" MODIFY ("USER_SALARY" NOT NULL ENABLE);
  ALTER TABLE "LOCALHOST"."USER_RECORDS" MODIFY ("USER_MANAGER" NOT NULL ENABLE);
